### ISSUE TITLE
Stream in Flutter Web Returns Value Only at the End

### ISSUE THREAD

**Issue by StroeAndreX** [anasfik/openai#103] opened 2023-10-10 13:27 UTC
I'm using the version 4.0.0, it seems that `OpenAI.instance.chat.createStream` only returns the value when it finishes the request. I've tried many things, but everything seems to fail. This only occurs on Flutter Web.

**Comment by Josecodesalot** [comment] 2023-10-17 03:17
Same here!

**Comment by Josecodesalot** [comment] 2023-11-02 01:55
@StroeAndreX  Can you reproduce on mobile? might be an issue with the HTTP pacakge

**Comment by anasfik** [comment] 2023-11-08 21:42
Hello @Josecodesalot.

Please upgrade to version 4.1.1 from [https://pub.dev/packages/dart_openai](https://pub.dev/packages/dart_openai) and confirm if you can still reproduce this issue with Flutter Web.

Thank you!

**Comment by wilinz** [comment] 2023-11-09 12:18
Because http_client_web uses xhr, and xhr does not support streaming responses, we should use fetch api on the web

**Comment by anasfik** [comment] 2023-11-13 17:34
@wilinz 
Can you help with that?

**Comment by Josecodesalot** [comment] 2023-11-14 17:44
> Hello @Josecodesalot.
> 
> Please upgrade to version 4.1.1 from https://pub.dev/packages/dart_openai and confirm if you can still reproduce this issue with Flutter Web.
> 
> Thank you!

Thanks so much for trying to do this fix, I tried to implement SSE streams in flutter web but they were not possible, Decided instead to implement this using JS and an interop for Flutter Web.

Hope it works out for people out there! cheers!

**Comment by wilinz** [comment] 2023-11-14 18:03
Can use FetchClient

```yaml
dependencies:
  fetch_client: ^1.0.2
```

```dart
      final fetchClient = FetchClient(mode: RequestMode.cors,credentials: RequestCredentials.cors);
      final resp = await OpenAI.instance.chat.create(model: model, messages: messages,client: fetchClient);
```

**Comment by anasfik** [comment] 2023-11-17 19:23
Hello @wilinz 
I exposed an API field `OpenAI.isWeb` that can take a bol option for whether the env is web, [so it can be used with Flutter](https://github.com/anasfik/openai#configure-the-package-for-web-environment-flutter-web).

if it is true, it uses the fetch_client package client for streaming methods, can you use `dart_openai` by pulling it from git in your Flutter project and see how it works.

**Comment by anasfik** [comment] 2023-11-17 19:59
Never mind the my previous comment, I made use of the if condiftions on `dart.library.js` and `dart.library.io`  to make it be usable dynamically without developer interaction via the previous `OpenAI.isWeb`.

I assume that now using the package normally should behave as expected with streaming responses, can you recheck please?

**Comment by StroeAndreX** [comment] 2023-11-17 21:06
Just upgraded to 4.1.4 and I can confirm that streaming actually works fine now! 

Thank you for the fix <3

**Comment by anasfik** [comment] 2023-11-18 00:01
Cool, Closing this.

**Closed by anasfik** 2023-11-18 00:01 UTC
